<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('permissions')->truncate();

        $permissions = [
            [
                'id' => 1,
                'display_name' => 'কনফিগারেশন দেখা',
                'name' => 'can-view-configuration',
                'guard_name' => 'web',
                'group_name' => 'Configuration Management',
                'is_active' => true,
            ],
            [
                'id' => 2,
                'display_name' => 'কনফিগারেশন আপডেট করা',
                'name' => 'can-edit-configuration',
                'guard_name' => 'web',
                'group_name' => 'Configuration Management',
                'is_active' => true,
            ],
            [
                'id' => 3,
                'display_name' => 'ইউজার তৈরী করা',
                'name' => 'can-create-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 4,
                'display_name' => 'ইউজার আপডেট করা',
                'name' => 'can-edit-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 5,
                'display_name' => 'ইউজার ডিলিট করা',
                'name' => 'can-delete-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 6,
                'display_name' => 'ইউজার দেখা',
                'name' => 'can-view-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 7,
                'display_name' => 'ইউজার ডিটেইলস দেখা',
                'name' => 'can-view-details-user',
                'guard_name' => 'web',
                'group_name' => 'User Management',
                'is_active' => true,
            ],
            [
                'id' => 8,
                'display_name' => 'রোল তৈরী করা',
                'name' => 'can-create-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 9,
                'display_name' => 'রোল আপডেট করা',
                'name' => 'can-edit-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 10,
                'display_name' => 'রোল ডিলিট করা',
                'name' => 'can-delete-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 11,
                'display_name' => 'রোল দেখা',
                'name' => 'can-view-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 12,
                'display_name' => 'রোল ডিটেইলস দেখা',
                'name' => 'can-view-details-role',
                'guard_name' => 'web',
                'group_name' => 'Role Management',
                'is_active' => true,
            ],
            [
                'id' => 13,
                'display_name' => 'পারমিশন তৈরী করা',
                'name' => 'can-create-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 14,
                'display_name' => 'পারমিশন আপডেট করা',
                'name' => 'can-edit-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 15,
                'display_name' => 'পারমিশন ডিলিট করা',
                'name' => 'can-delete-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 16,
                'display_name' => 'পারমিশন দেখা',
                'name' => 'can-view-permission',
                'guard_name' => 'web',
                'group_name' => 'Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 17,
                'display_name' => 'কোম্পানি তৈরী করা',
                'name' => 'can-create-company',
                'guard_name' => 'web',
                'group_name' => 'Company Management',
                'is_active' => true,
            ],
            [
                'id' => 18,
                'display_name' => 'কোম্পানি আপডেট করা',
                'name' => 'can-edit-company',
                'guard_name' => 'web',
                'group_name' => 'Company Management',
                'is_active' => true,
            ],
            [
                'id' => 19,
                'display_name' => 'কোম্পানি দেখা',
                'name' => 'can-view-company',
                'guard_name' => 'web',
                'group_name' => 'Company Management',
                'is_active' => true,
            ],
            [
                'id' => 20,
                'display_name' => 'কোম্পানি ডিটেইলস দেখা',
                'name' => 'can-view-details-company',
                'guard_name' => 'web',
                'group_name' => 'Company Management',
                'is_active' => true,
            ],
            [
                'id' => 21,
                'display_name' => 'আইটেম দেখা',
                'name' => 'can-view-item',
                'guard_name' => 'web',
                'group_name' => 'Item Management',
                'is_active' => true,
            ],
            [
                'id' => 22,
                'display_name' => 'আইটেম তৈরী করা',
                'name' => 'can-create-item',
                'guard_name' => 'web',
                'group_name' => 'Item Management',
                'is_active' => true,
            ],
            [
                'id' => 23,
                'display_name' => 'আইটেম আপডেট করা',
                'name' => 'can-edit-item',
                'guard_name' => 'web',
                'group_name' => 'Item Management',
                'is_active' => true,
            ],
            [
                'id' => 24,
                'display_name' => 'আইটেম ডিলিট করা',
                'name' => 'can-delete-item',
                'guard_name' => 'web',
                'group_name' => 'Item Management',
                'is_active' => true,
            ],
            [
                'id' => 25,
                'display_name' => 'আইটেম ইউনিট দেখা',
                'name' => 'can-view-item-unit',
                'guard_name' => 'web',
                'group_name' => 'Item Unit Management',
                'is_active' => true,
            ],
            [
                'id' => 26,
                'display_name' => 'আইটেম ইউনিট তৈরী করা',
                'name' => 'can-create-item-unit',
                'guard_name' => 'web',
                'group_name' => 'Item Unit Management',
                'is_active' => true,
            ],
            [
                'id' => 27,
                'display_name' => 'আইটেম ইউনিট আপডেট করা',
                'name' => 'can-edit-item-unit',
                'guard_name' => 'web',
                'group_name' => 'Item Unit Management',
                'is_active' => true,
            ],
            [
                'id' => 28,
                'display_name' => 'আইটেম ইউনিট ডিলিট করা',
                'name' => 'can-delete-item-unit',
                'guard_name' => 'web',
                'group_name' => 'Item Unit Management',
                'is_active' => true,
            ],
            [
                'id' => 29,
                'display_name' => 'ব্র্যান্ড দেখা',
                'name' => 'can-view-brand',
                'guard_name' => 'web',
                'group_name' => 'Brand Management',
                'is_active' => true,
            ],
            [
                'id' => 30,
                'display_name' => 'ব্র্যান্ড তৈরী করা',
                'name' => 'can-create-brand',
                'guard_name' => 'web',
                'group_name' => 'Brand Management',
                'is_active' => true,
            ],
            [
                'id' => 31,
                'display_name' => 'ব্র্যান্ড আপডেট করা',
                'name' => 'can-edit-brand',
                'guard_name' => 'web',
                'group_name' => 'Brand Management',
                'is_active' => true,
            ],
            [
                'id' => 32,
                'display_name' => 'ব্র্যান্ড ডিলিট করা',
                'name' => 'can-delete-brand',
                'guard_name' => 'web',
                'group_name' => 'Brand Management',
                'is_active' => true,
            ],
            [
                'id' => 33,
                'display_name' => 'ফিস্কাল ইয়ার তৈরী করা',
                'name' => 'can-create-fiscal-year',
                'guard_name' => 'web',
                'group_name' => 'Fiscal Year Management',
                'is_active' => true,
            ],
            [
                'id' => 34,
                'display_name' => 'ফিস্কাল ইয়ার দেখা',
                'name' => 'can-view-fiscal-year',
                'guard_name' => 'web',
                'group_name' => 'Fiscal Year Management',
                'is_active' => true,
            ],
            [
                'id' => 35,
                'display_name' => 'ফিস্কাল ইয়ার আপডেট করা',
                'name' => 'can-edit-fiscal-year',
                'guard_name' => 'web',
                'group_name' => 'Fiscal Year Management',
                'is_active' => true,
            ],
            [
                'id' => 36,
                'display_name' => 'ফিস্কাল ইয়ার ডিলিট করা',
                'name' => 'can-delete-fiscal-year',
                'guard_name' => 'web',
                'group_name' => 'Fiscal Year Management',
                'is_active' => true,
            ],
            [
                'id' => 37,
                'display_name' => 'সাবস্ক্রিপশন দেখা',
                'name' => 'can-view-subscription',
                'guard_name' => 'web',
                'group_name' => 'Subscription Management',
                'is_active' => true,
            ],
            [
                'id' => 38,
                'display_name' => 'সাবস্ক্রিপশন তৈরী করা',
                'name' => 'can-create-subscription',
                'guard_name' => 'web',
                'group_name' => 'Subscription Management',
                'is_active' => true,
            ],
            [
                'id' => 39,
                'display_name' => 'সাবস্ক্রিপশন আপডেট করা',
                'name' => 'can-edit-subscription',
                'guard_name' => 'web',
                'group_name' => 'Subscription Management',
                'is_active' => true,
            ],
            [
                'id' => 40,
                'display_name' => 'সাবস্ক্রিপশন প্ল্যান তৈরী করা',
                'name' => 'can-create-subscription-plan',
                'guard_name' => 'web',
                'group_name' => 'Subscription Plan Management',
                'is_active' => true,
            ],
            [
                'id' => 41,
                'display_name' => 'সাবস্ক্রিপশন প্ল্যান আপডেট করা',
                'name' => 'can-edit-subscription-plan',
                'guard_name' => 'web',
                'group_name' => 'Subscription Plan Management',
                'is_active' => true,
            ],
            [
                'id' => 42,
                'display_name' => 'সাবস্ক্রিপশন প্ল্যান দেখা',
                'name' => 'can-view-subscription-plan',
                'guard_name' => 'web',
                'group_name' => 'Subscription Plan Management',
                'is_active' => true,
            ],
            [
                'id' => 43,
                'display_name' => 'সাবস্ক্রিপশন প্ল্যান ডিটেইলস দেখা',
                'name' => 'can-view-details-subscription-plan',
                'guard_name' => 'web',
                'group_name' => 'Subscription Plan Management',
                'is_active' => true,
            ],
            [
                'id' => 44,
                'display_name' => 'সাবস্ক্রিপশন প্ল্যান ফিচার তৈরী করা',
                'name' => 'can-create-subscription-plan-feature',
                'guard_name' => 'web',
                'group_name' => 'Subscription Plan Feature Management',
                'is_active' => true,
            ],
            [
                'id' => 45,
                'display_name' => 'সাবস্ক্রিপশন প্ল্যান ফিচার আপডেট করা',
                'name' => 'can-edit-subscription-plan-feature',
                'guard_name' => 'web',
                'group_name' => 'Subscription Plan Feature Management',
                'is_active' => true,
            ],
            [
                'id' => 46,
                'display_name' => 'সাবস্ক্রিপশন প্ল্যান ফিচার দেখা',
                'name' => 'can-view-subscription-plan-feature',
                'guard_name' => 'web',
                'group_name' => 'Subscription Plan Feature Management',
                'is_active' => true,
            ],
            [
                'id' => 47,
                'display_name' => 'সাবস্ক্রিপশন প্ল্যান ফিচার ডিটেইলস দেখা',
                'name' => 'can-view-details-subscription-plan-feature',
                'guard_name' => 'web',
                'group_name' => 'Subscription Plan Feature Management',
                'is_active' => true,
            ],
            [
                'id' => 48,
                'display_name' => 'টিনেন্ট পারমিশন তৈরী করা',
                'name' => 'can-create-tenant-permission',
                'guard_name' => 'web',
                'group_name' => 'Tenant Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 49,
                'display_name' => 'টিনেন্ট পারমিশন আপডেট করা',
                'name' => 'can-edit-tenant-permission',
                'guard_name' => 'web',
                'group_name' => 'Tenant Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 50,
                'display_name' => 'টিনেন্ট পারমিশন দেখা',
                'name' => 'can-view-tenant-permission',
                'guard_name' => 'web',
                'group_name' => 'Tenant Permission Management',
                'is_active' => true,
            ],
            [
                'id' => 51,
                'display_name' => 'টিনেন্ট রোল তৈরী করা',
                'name' => 'can-create-tenant-role',
                'guard_name' => 'web',
                'group_name' => 'Tenant Role Management',
                'is_active' => true,
            ],
            [
                'id' => 52,
                'display_name' => 'টিনেন্ট রোল আপডেট করা',
                'name' => 'can-edit-tenant-role',
                'guard_name' => 'web',
                'group_name' => 'Tenant Role Management',
                'is_active' => true,
            ],
            [
                'id' => 53,
                'display_name' => 'টিনেন্ট রোল দেখা',
                'name' => 'can-view-tenant-role',
                'guard_name' => 'web',
                'group_name' => 'Tenant Role Management',
                'is_active' => true,
            ],
            [
                'id' => 54,
                'display_name' => 'টিনেন্ট রোল ডিটেইলস দেখা',
                'name' => 'can-view-details-tenant-role',
                'guard_name' => 'web',
                'group_name' => 'Tenant Role Management',
                'is_active' => true,
            ],
            [
                'id' => 55,
                'display_name' => 'চাকরির পদ তৈরী করা',
                'name' => 'can-create-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 56,
                'display_name' => 'চাকরির পদ আপডেট করা',
                'name' => 'can-edit-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 57,
                'display_name' => 'চাকরির পদ ডিলিট করা',
                'name' => 'can-delete-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 58,
                'display_name' => 'চাকরির পদ দেখা',
                'name' => 'can-view-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 59,
                'display_name' => 'চাকরির পদের ডিটেইলস দেখা',
                'name' => 'can-view-details-job-position',
                'guard_name' => 'web',
                'group_name' => 'Job Position Management',
                'is_active' => true,
            ],
            [
                'id' => 60,
                'display_name' => 'পরিশোধের মাধ্যম তৈরী করা',
                'name' => 'can-create-payment-method',
                'guard_name' => 'web',
                'group_name' => 'Payment Method Management',
                'is_active' => true,
            ],
            [
                'id' => 61,
                'display_name' => 'পরিশোধের মাধ্যম আপডেট করা',
                'name' => 'can-edit-payment-method',
                'guard_name' => 'web',
                'group_name' => 'Payment Method Management',
                'is_active' => true,
            ],
            [
                'id' => 62,
                'display_name' => 'পরিশোধের মাধ্যম ডিলিট করা',
                'name' => 'can-delete-payment-method',
                'guard_name' => 'web',
                'group_name' => 'Payment Method Management',
                'is_active' => true,
            ],
            [
                'id' => 63,
                'display_name' => 'পরিশোধের মাধ্যম দেখা',
                'name' => 'can-view-payment-method',
                'guard_name' => 'web',
                'group_name' => 'Payment Method Management',
                'is_active' => true,
            ],
            [
                'id' => 64,
                'display_name' => 'পরিশোধের মাধ্যমের ডিটেইলস দেখা',
                'name' => 'can-view-details-payment-method',
                'guard_name' => 'web',
                'group_name' => 'Payment Method Management',
                'is_active' => true,
            ]
        ];

        foreach ($permissions as $permission) {
            Permission::create($permission);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
